# 1
name: Android CI
# 2
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 3
jobs:
  build-and-test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository in ubuntu's file system
        uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: Print contents in current directory
        run: ls -la
      - name: Unit tests
        run: ./gradlew testDebugUnitTest


